
import { PlaceHolderImages } from "@/lib/placeholder-images";

export const blogPosts = [
    {
        id: "transformation-numerique-bunia",
        title: "Bunia à l'Ère du Numérique : Comment la Technologie Façonne l'Avenir de la Ville",
        category: "Développement Local",
        author: "Prince Ongala",
        image: PlaceHolderImages.find(p => p.id === 'blog-bunia-digital'),
        excerpt: "Découvrez comment les innovations technologiques, de la finance mobile à l'éducation en ligne, redessinent le paysage économique et social de Bunia.",
        date: "20 Oct, 2024",
    },
    {
        id: "agritech-ituri",
        title: "L'AgriTech en Ituri : Une Révolution Silencieuse pour les Agriculteurs de Bunia",
        category: "Technologie Agricole",
        author: "Isaac Diavo",
        image: PlaceHolderImages.find(p => p.id === 'blog-agritech'),
        excerpt: "Des drones pour la cartographie des champs aux applications de gestion de récoltes, l'agriculture en Ituri se modernise et gagne en efficacité.",
        date: "15 Oct, 2024",
    },
    {
        id: "commerce-bunia-digitalisation",
        title: "Du Marché Central de Bunia à la Boutique en Ligne",
        category: "E-commerce",
        author: "Merite Mufungizi",
        image: PlaceHolderImages.find(p => p.id === 'blog-bunia-commerce'),
        excerpt: "Un guide pratique pour les commerçants de Bunia souhaitant digitaliser leur activité, attirer plus de clients et gérer leurs opérations efficacement.",
        date: "12 Oct, 2024",
    },
    {
        id: "fintech-bunia",
        title: "Le Boom de la Finance Mobile à Bunia : Inclusion Financière et Nouvelles Opportunités",
        category: "FinTech",
        author: "Dimex Mwanzita",
        image: PlaceHolderImages.find(p => p.id === 'blog-fintech-rdc'),
        excerpt: "L'adoption massive du mobile money transforme le commerce et la vie quotidienne, ouvrant la voie à une nouvelle ère d'inclusion financière pour tous.",
        date: "08 Oct, 2024",
    },
    {
        id: "education-universite-bunia",
        title: "L'impact des TICE dans les universités de Bunia : Entre défis et opportunités",
        category: "Éducation Supérieure",
        author: "Jacques Uwonda",
        image: PlaceHolderImages.find(p => p.id === 'blog-university-bunia'),
        excerpt: "Analyse de l'intégration des technologies de l'information et de la communication dans l'enseignement supérieur à Bunia et de leur rôle dans la formation des futurs leaders.",
        date: "02 Oct, 2024",
    },
    {
        id: "education-tech-bunia",
        title: "EdTech en RDC : Comment les Plateformes en Ligne Renforcent l'Éducation à Bunia",
        category: "Éducation",
        author: "Eric Pimbo",
        image: PlaceHolderImages.find(p => p.id === 'blog-edtech-rdc'),
        excerpt: "Analyse des solutions d'e-learning et de leur impact sur l'accès à une éducation de qualité pour les jeunes de la région.",
        date: "29 Sep, 2024",
    },
    {
        id: "cybersecurite-pme-bunia",
        title: "Cybersécurité : Les Défis et Solutions pour les PME de Bunia",
        category: "Cybersécurité",
        author: "Dimex Mwanzita",
        image: PlaceHolderImages.find(p => p.id === 'blog-cybersecurity'),
        excerpt: "Alors que les entreprises se numérisent, la protection des données devient cruciale. Nos experts partagent des conseils pratiques pour sécuriser votre activité.",
        date: "22 Sep, 2024",
    },
    {
        id: "religion-technologie-bunia",
        title: "La Technologie au Service des Communautés Religieuses de Bunia",
        category: "Technologie & Société",
        author: "Isaac Diavo",
        image: PlaceHolderImages.find(p => p.id === 'blog-religion-tech'),
        excerpt: "Comment les outils numériques aident les églises et organisations religieuses à mieux gérer leurs membres, à communiquer et à étendre leur portée.",
        date: "18 Sep, 2024",
    },
    {
        id: "energie-solaire-ituri",
        title: "L'Énergie Solaire : Le Moteur de l'Innovation Technologique en Ituri",
        category: "Énergies Renouvelables",
        author: "Prince Ongala",
        image: PlaceHolderImages.find(p => p.id === 'blog-solar-rdc'),
        excerpt: "L'accès à une énergie fiable et abordable grâce au solaire est un catalyseur pour le déploiement de nouvelles solutions numériques dans les zones urbaines et rurales.",
        date: "12 Sep, 2024",
    },
    {
        id: "sante-connectee-rdc",
        title: "La Santé Connectée : Améliorer l'Accès aux Soins en RDC grâce à la Télémédecine",
        category: "Santé",
        author: "Merite Mufungizi",
        image: PlaceHolderImages.find(p => p.id === 'blog-health-rdc'),
        excerpt: "La télémédecine et les dossiers médicaux numériques promettent de révolutionner le secteur de la santé, même dans les régions les plus reculées.",
        date: "28 Aoû, 2024",
    },
    {
        id: "education-ecole-ituri",
        title: "Numérisation des Écoles en Ituri : ITSS Accompagne la Transition",
        category: "Éducation",
        author: "Isaac Diavo",
        image: PlaceHolderImages.find(p => p.id === 'blog-school-ituri'),
        excerpt: "Découvrez comment ITSS aide les écoles primaires et secondaires à intégrer le numérique pour améliorer l'administration et l'apprentissage.",
        date: "21 Aoû, 2024",
    },
    {
        id: "hub-innovation-bunia",
        title: "Créer un Hub d'Innovation à Bunia : Notre Vision pour l'Écosystème Tech Local",
        category: "Innovation",
        author: "Prince Ongala",
        image: PlaceHolderImages.find(p => p.id === 'blog-innovation-hub'),
        excerpt: "ITSS s'engage à soutenir les talents locaux en créant un espace de collaboration, de formation et d'incubation pour les startups de demain.",
        date: "15 Aoû, 2024",
    }
];
